### ISSUE TITLE
informal request: also importing unicode DUCET db

### ISSUE THREAD

**Issue by VUJohnAD** [nitely/nim-unicodedb#28]
generated from discussion on forum: https://forum.nim-lang.org/t/10137

By default, Nim's ability to sort or compare Unicode strings is not Unicode-compliant. One can either sort generically (treating a string as a series of bytes), or as arrays of Runes compared as 32-bit uints. Neither of which are correct. Even in basic ASCII that creates a sort order of A B a b rather than the correct A a B b.

More details in the forum thread. But part of solving this would be about having the Unicode consortium's Unicode Collation Algorithm database available. The database is called DUCET and the latest is available at http://www.unicode.org/Public/UCA/latest/allkeys.txt

**Comment by nitely** [comment]
we can add that DB to this lib. But be aware (non-generic) sorting depends on the language (pretty sure) see https://unicode.org/reports/tr10/#Omitted_Contractions

**Comment by JohnAD** [comment]
I plan on using this for key sorting with JSON files, and the JSON spec does not allow for the specification of a language for the file.

So, it is the generic context that I'm needing.

Thanks for helping with this! Ideally, I'll create a nimble package that allows for generic Unicode sorting and comparison when done.

If I get real ambitious I'll later add language specific sorting. But that does not look like an easy task; not even close.

(@VUJohnAD == @JohnAD; I accidentally posted with one of my work accounts :grin:  )
