### ISSUE TITLE
east_asian_width ?

### ISSUE THREAD

**Issue by 2vg** [nitely/nim-unicodedb#3]
Is there a way to get the display width of characters like east_asian_width ?

**Comment by nitely** [comment]
Interesting. I'll add the data later today. However, you'll still need a font that follows the rules (for example unifont[0]), so you can't rely on whatever font the user has installed [1]

[0] http://unifoundry.com/unifont.html
[1] https://denisbider.blogspot.com.ar/2015/09/when-monospace-fonts-arent-unicode.html

**Comment by nitely** [comment]
btw, to calculate the width in (most?) terminals you can just use libc's `wcwidth`, but that's broken for anything else (i.e: modern terminal emulators, text editors, etc).

What're you going to use this for anyway?

**Comment by 2vg** [comment]
thx !
I'm going to make a shell in Nim.
I was troubled with the display width of multibyte characters.

Yeah, I saw wcwidth but I didn't know how to import...

**Comment by nitely** [comment]
That's a cool project. I think this is what I'll do: access to `EastAsianWidth` data, `unifont` data, and `wcwidth` data.

AFAIK `wcwidth` supports unicode 5, so it's quite outdated.  tr11 (EastAsianWidth spec) does not cover everything and leaves some things up to implementations. The closest thing to a spec seems to be `unifont`.

But in your case, I'm not sure which one is the right choice. A shell can run in any terminal, right? so, you would want to use whatever the terminal is using. That's `wcwidth` in most unix terminals, or `unifont` in some modern terminal emulators :confused:

**Comment by nitely** [comment]
> Yeah, I saw wcwidth but I didn't know how to import...

This does the trick for me:

```nim
proc wcwidth(c: cint): cint {.header: "<wchar.h>".}

assert wcwidth('a'.ord) == 1
```

But a lot of chars like `"弢".runeAt(0).int32` return `-1` meaning the char was added in a newer unicode version. I guess a width of 2 cells should be used then, but I'm not sure.

**Comment by 2vg** [comment]
hmm, wcwidth seems strict...
saw your commit.
That's a awesome job ...!
The scenes to use are limited, but there will be people who need it !

**Comment by nitely** [comment]
I don't know much about shells TBH, but I've read that it's better to calculate the width the same way the terminal does [0] . `fish-shell` had plenty of bugs for not doing that [1] [2] [3] .

> Edit: It only returns >= 0 for ascii chars, everything else is -1. There must be something wrong with that import.

That seems to be a RHEL/gnome-terminal issue (I'm on Fedora), but it should work on other systems.

About the commit, I'll make a release once I add some tests and make sure it works as expected :smile: 

[0] https://github.com/fish-shell/fish-shell/pull/4816#issuecomment-375770611
[1] https://github.com/fish-shell/fish-shell/issues/2652
[2] https://github.com/fish-shell/fish-shell/issues/2199
[3] https://github.com/fish-shell/fish-shell/issues/750

**Comment by nitely** [comment]
ok, I just released a new version with access to the east-asian-width table. I did not end up adding the unifont[0] and `wcwidth` data, but I may add them at some point.

Feel free to close this.

[0] https://gist.github.com/nitely/62b281dcfd15490e1ed21296d6be3113

**Comment by 2vg** [comment]
I tried it. 
awesome... It is a very great job !!!
Thanks nitely ♡
